Update post-checkout
Signed-off-by: DAVID OKEAMAH  <whitneykiss741@gmail.com>

diff --git a/.husky/post-checkout b/.husky/post-checkout
--- a/.husky/post-checkout
+++ b/.husky/post-checkout
@@ -1,3 +1,11 @@
 #!/bin/sh
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"; exit 2; }
+
+# Check if git-lfs is installed
+if ! command -v git-lfs >/dev/null 2>&1; then
+  echo >&2 "\nThis repository is configured to use Git LFS, but 'git-lfs' was not found in your PATH."
+  echo >&2 "If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"
+  exit 2
+fi
+
+# Call the Git LFS post-checkout command with the passed arguments
 git lfs post-checkout "$@"
